Default: &defaults
  user: renters
  password: reality
  host: localhost
  port: 5432
  database: renters
  poolsize: 10

Development:
  <<: *defaults

# Non-Development reads from DATABASE_URL via Helpers.Heroku
