Default: &defaults
  user: renters
  password: reality
  host: localhost
  port: 5432
  database: renters
  poolsize: 10

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
  user: yphlhbhmzthocg
  password: 4KE6f7tENj2YaAh43vWoCqfMAo
  host: ec2-54-243-228-169.compute-1.amazonaws.com
  port: 5432
  database: dfh57p6tk1gqbl
  sslmode: require
